#!/bin/bash

# Check if an argument is provided
if [ $# -ne 1 ]; then
    echo "Usage: puddle <argument>"
    exit 1
fi

# Call the Python script with the provided argument
python pud_interpret.py "$1"
